# Feature Phone Workflow - Full Edition
# Generic keypad phone with a rounded shell and clean proportions

name: feature_phone_workflow
description: Creates a realistic keypad phone with rounded shell, keypad, screen, and antenna
category: electronics
author: blender-ai-mcp
version: "5.1.0"

trigger_keywords:
  - feature phone
  - keypad phone
  - button phone
  - classic phone
  - old phone
  - retro phone
  - telefon przyciskowy
  - telefon z klawiatura
  - stary telefon

sample_prompts:
  - "create a classic keypad phone"
  - "make a feature phone"
  - "stworz telefon przyciskowy"

defaults:
  # Phone dimensions (generic feature phone)
  width: 0.077
  depth: 0.020
  height: 0.209

  # Cleanup option
  clean_scene: false

  # Bevel/Subsurf settings
  body_bevel_width: 0.0025
  body_bevel_segments: 5
  body_subsurf_levels: 2

parameters:
  width:
    type: float
    range: [0.05, 0.10]
    default: 0.077
    description: Phone width (X)
    semantic_hints: [width, size]
    group: dimensions

  height:
    type: float
    range: [0.15, 0.25]
    default: 0.209
    description: Phone height (Z)
    semantic_hints: [height, size]
    group: dimensions

  depth:
    type: float
    range: [0.015, 0.035]
    default: 0.020
    description: Phone depth (Y)
    semantic_hints: [depth, thickness]
    group: dimensions

  clean_scene:
    type: bool
    default: false
    description: Clean scene before building
    group: workflow

  body_bevel_width:
    type: float
    range: [0.001, 0.006]
    default: 0.0025
    description: Bevel width for body
    group: style

  body_bevel_segments:
    type: int
    range: [2, 6]
    default: 5
    description: Bevel segments for smoothness
    group: style

  body_subsurf_levels:
    type: int
    range: [0, 3]
    default: 2
    description: Subdivision levels for body smoothness
    group: style

steps:
  # =============================
  # SCENE PREP
  # =============================
  - tool: scene_clean_scene
    params:
      keep_lights_and_cameras: false
    condition: "clean_scene"
    description: Optional scene cleanup

  - tool: collection_manage
    params: {action: "create", collection_name: "Phone_Body"}

  - tool: collection_manage
    params: {action: "create", collection_name: "Phone_Front"}

  - tool: collection_manage
    params: {action: "create", collection_name: "Phone_Screen"}

  - tool: collection_manage
    params: {action: "create", collection_name: "Phone_Buttons"}

  # =============================
  # BODY - Main Shell
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "body_shell"
    description: Main body shell

  - tool: modeling_transform_object
    params:
      name: "body_shell"
      scale:
        - "$CALCULATE(width / 2)"
        - "$CALCULATE(depth / 2)"
        - "$CALCULATE(height / 2)"
      location:
        - 0.0
        - 0.0
        - 0.0

  - tool: lattice_create
    params:
      name: "body_lattice"
      target_object: "body_shell"
      points_u: 2
      points_v: 2
      points_w: 4
      interpolation: "KEY_BSPLINE"
    description: Lattice for gentle body taper and curvature

  - tool: lattice_bind
    params:
      object_name: "body_shell"
      lattice_name: "body_lattice"

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [12, 14]
      offset:
        - "$CALCULATE(width * 0.03)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [13, 15]
      offset:
        - "$CALCULATE(-width * 0.03)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [12, 13]
      offset:
        - 0.0
        - "$CALCULATE(depth * 0.05)"
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [14, 15]
      offset:
        - 0.0
        - "$CALCULATE(-depth * 0.05)"
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [0, 2]
      offset:
        - "$CALCULATE(width * 0.02)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [1, 3]
      offset:
        - "$CALCULATE(-width * 0.02)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [0, 1]
      offset:
        - 0.0
        - "$CALCULATE(depth * 0.03)"
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [2, 3]
      offset:
        - 0.0
        - "$CALCULATE(-depth * 0.03)"
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [4, 6, 8, 10]
      offset:
        - "$CALCULATE(-width * 0.01)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [5, 7, 9, 11]
      offset:
        - "$CALCULATE(width * 0.01)"
        - 0.0
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [4, 5, 8, 9]
      offset:
        - 0.0
        - "$CALCULATE(-depth * 0.01)"
        - 0.0
      relative: true

  - tool: lattice_edit_point
    params:
      lattice_name: "body_lattice"
      point_index: [6, 7, 10, 11]
      offset:
        - 0.0
        - "$CALCULATE(depth * 0.01)"
        - 0.0
      relative: true

  - tool: scene_hide_object
    params:
      object_name: "body_lattice"
      hide: true

  - tool: modeling_add_modifier
    params:
      name: "body_shell"
      modifier_type: "BEVEL"
      properties:
        width: "$body_bevel_width"
        segments: "$body_bevel_segments"
        limit_method: "ANGLE"
        angle_limit: 0.523599
    description: Bevel body for rounded edges

  - tool: modeling_add_modifier
    params:
      name: "body_shell"
      modifier_type: "SUBSURF"
      properties:
        levels: "$body_subsurf_levels"
        render_levels: "$body_subsurf_levels"

  # =============================
  # BODY - Back Panel (Battery Cover)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "back_panel"
    description: Battery cover

  - tool: modeling_transform_object
    params:
      name: "back_panel"
      scale:
        - "$CALCULATE(width * 0.94 / 2)"
        - "$CALCULATE(depth * 0.22 / 2)"
        - "$CALCULATE(height * 0.62 / 2)"
      location:
        - 0.0
        - "$CALCULATE(depth * 0.39)"
        - "$CALCULATE(-height * 0.06)"

  - tool: modeling_add_modifier
    params:
      name: "back_panel"
      modifier_type: "BEVEL"
      properties:
        width: 0.0015
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # BODY - Antenna
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "antenna_base"
    description: Antenna base

  - tool: modeling_transform_object
    params:
      name: "antenna_base"
      scale:
        - "$CALCULATE(width * 0.035)"
        - "$CALCULATE(width * 0.035)"
        - "$CALCULATE(depth * 0.12)"
      location:
        - "$CALCULATE(width * 0.26)"
        - "$CALCULATE(depth * 0.18)"
        - "$CALCULATE(height * 0.48)"

  - tool: modeling_add_modifier
    params:
      name: "antenna_base"
      modifier_type: "BEVEL"
      properties:
        width: 0.0006
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.523599

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "antenna_rod"
    description: Antenna rod

  - tool: modeling_transform_object
    params:
      name: "antenna_rod"
      scale:
        - "$CALCULATE(width * 0.012)"
        - "$CALCULATE(width * 0.012)"
        - "$CALCULATE(height * 0.12)"
      location:
        - "$CALCULATE(width * 0.26)"
        - "$CALCULATE(depth * 0.18)"
        - "$CALCULATE(height * 0.5 + height * 0.12)"

  - tool: modeling_add_modifier
    params:
      name: "antenna_rod"
      modifier_type: "BEVEL"
      properties:
        width: 0.0003
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # BODY - Charging Port
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "charging_port"
    description: Charging port opening

  - tool: modeling_transform_object
    params:
      name: "charging_port"
      scale:
        - "$CALCULATE(width * 0.16 / 2)"
        - "$CALCULATE(depth * 0.25 / 2)"
        - "$CALCULATE(height * 0.02 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.52)"
        - "$CALCULATE(-height * 0.48)"

  - tool: modeling_add_modifier
    params:
      name: "charging_port"
      modifier_type: "BEVEL"
      properties:
        width: 0.0005
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # FRONT - Lower Arc (Top curve with speaker)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "front_lower_arc"
    description: Top curved section

  - tool: modeling_transform_object
    params:
      name: "front_lower_arc"
      scale:
        - "$CALCULATE(width * 0.88 / 2)"
        - "$CALCULATE(depth * 0.10 / 2)"
        - "$CALCULATE(height * 0.10 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.48)"
        - "$CALCULATE(height * 0.34)"

  - tool: modeling_add_modifier
    params:
      name: "front_lower_arc"
      modifier_type: "BEVEL"
      properties:
        width: 0.002
        segments: 3
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # FRONT - Top Eyelet (Speaker grille)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "front_top_eyelet"
    description: Speaker/earpiece grille

  - tool: modeling_transform_object
    params:
      name: "front_top_eyelet"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.20)"
        - "$CALCULATE(width * 0.06)"
        - "$CALCULATE(depth * 0.18)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.52)"
        - "$CALCULATE(height * 0.34)"

  # =============================
  # FRONT - Screen Frame
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "front_screen_frame"
    description: Screen frame

  - tool: modeling_transform_object
    params:
      name: "front_screen_frame"
      scale:
        - "$CALCULATE(width * 0.80 / 2)"
        - "$CALCULATE(depth * 0.08 / 2)"
        - "$CALCULATE(height * 0.30 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.49)"
        - "$CALCULATE(height * 0.12)"

  - tool: modeling_add_modifier
    params:
      name: "front_screen_frame"
      modifier_type: "BEVEL"
      properties:
        width: 0.002
        segments: 3
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # FRONT - Screen Glass
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "screen_glass"
    description: Screen glass

  - tool: modeling_transform_object
    params:
      name: "screen_glass"
      scale:
        - "$CALCULATE(width * 0.64 / 2)"
        - "$CALCULATE(depth * 0.02 / 2)"
        - "$CALCULATE(height * 0.22 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.51)"
        - "$CALCULATE(height * 0.11)"

  # =============================
  # FRONT - Speaker Grille (Keypad housing)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "front_speaker_grille"
    description: Keypad housing

  - tool: modeling_transform_object
    params:
      name: "front_speaker_grille"
      scale:
        - "$CALCULATE(width * 0.90 / 2)"
        - "$CALCULATE(depth * 0.12 / 2)"
        - "$CALCULATE(height * 0.38 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.50)"
        - "$CALCULATE(-height * 0.20)"

  - tool: modeling_add_modifier
    params:
      name: "front_speaker_grille"
      modifier_type: "BEVEL"
      properties:
        width: 0.002
        segments: 3
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # FRONT - Keypad Ribs
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "front_keypad_ribs"
    description: Keypad texture area

  - tool: modeling_transform_object
    params:
      name: "front_keypad_ribs"
      scale:
        - "$CALCULATE(width * 0.78 / 2)"
        - "$CALCULATE(depth * 0.04 / 2)"
        - "$CALCULATE(height * 0.22 / 2)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.52)"
        - "$CALCULATE(-height * 0.32)"

  - tool: modeling_add_modifier
    params:
      name: "front_keypad_ribs"
      modifier_type: "BEVEL"
      properties:
        width: 0.0008
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # FRONT - Side Trims
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "side_trim_left"
    description: Left side trim

  - tool: modeling_transform_object
    params:
      name: "side_trim_left"
      scale:
        - "$CALCULATE(width * 0.05 / 2)"
        - "$CALCULATE(depth * 0.16 / 2)"
        - "$CALCULATE(height * 0.60 / 2)"
      location:
        - "$CALCULATE(-width * 0.47)"
        - "$CALCULATE(-depth * 0.42)"
        - "$CALCULATE(height * 0.02)"

  - tool: modeling_add_modifier
    params:
      name: "side_trim_left"
      modifier_type: "BEVEL"
      properties:
        width: 0.002
        segments: 3
        limit_method: "ANGLE"
        angle_limit: 0.523599

  - tool: modeling_create_primitive
    params:
      primitive_type: Cube
      name: "side_trim_right"
    description: Right side trim

  - tool: modeling_transform_object
    params:
      name: "side_trim_right"
      scale:
        - "$CALCULATE(width * 0.05 / 2)"
        - "$CALCULATE(depth * 0.16 / 2)"
        - "$CALCULATE(height * 0.60 / 2)"
      location:
        - "$CALCULATE(width * 0.47)"
        - "$CALCULATE(-depth * 0.42)"
        - "$CALCULATE(height * 0.02)"

  - tool: modeling_add_modifier
    params:
      name: "side_trim_right"
      modifier_type: "BEVEL"
      properties:
        width: 0.002
        segments: 3
        limit_method: "ANGLE"
        angle_limit: 0.523599

  # =============================
  # BUTTONS - Navigation
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "button_dpad"
    description: D-pad navigation

  - tool: modeling_transform_object
    params:
      name: "button_dpad"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.19)"
        - "$CALCULATE(width * 0.19)"
        - "$CALCULATE(depth * 0.14)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.16)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "button_call"
    description: Call button

  - tool: modeling_transform_object
    params:
      name: "button_call"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.12)"
        - "$CALCULATE(height * 0.035)"
        - "$CALCULATE(depth * 0.11)"
      location:
        - "$CALCULATE(-width * 0.27)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.16)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "button_end"
    description: End button

  - tool: modeling_transform_object
    params:
      name: "button_end"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.12)"
        - "$CALCULATE(height * 0.035)"
        - "$CALCULATE(depth * 0.11)"
      location:
        - "$CALCULATE(width * 0.27)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.16)"

  # =============================
  # BUTTONS - Soft keys
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "button_soft_left"
    description: Left soft key

  - tool: modeling_transform_object
    params:
      name: "button_soft_left"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.14)"
        - "$CALCULATE(height * 0.022)"
        - "$CALCULATE(depth * 0.10)"
      location:
        - "$CALCULATE(-width * 0.23)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.10)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "button_soft_right"
    description: Right soft key

  - tool: modeling_transform_object
    params:
      name: "button_soft_right"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.14)"
        - "$CALCULATE(height * 0.022)"
        - "$CALCULATE(depth * 0.10)"
      location:
        - "$CALCULATE(width * 0.23)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.10)"

  # =============================
  # KEYPAD - Row 1 (1-2-3)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_1"

  - tool: modeling_transform_object
    params:
      name: "key_1"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(-width * 0.26)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.30)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_2"

  - tool: modeling_transform_object
    params:
      name: "key_2"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.30)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_3"

  - tool: modeling_transform_object
    params:
      name: "key_3"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(width * 0.26)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.30)"

  # =============================
  # KEYPAD - Row 2 (4-5-6)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_4"

  - tool: modeling_transform_object
    params:
      name: "key_4"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(-width * 0.25)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.38)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_5"

  - tool: modeling_transform_object
    params:
      name: "key_5"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.38)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_6"

  - tool: modeling_transform_object
    params:
      name: "key_6"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(width * 0.25)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.38)"

  # =============================
  # KEYPAD - Row 3 (7-8-9)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_7"

  - tool: modeling_transform_object
    params:
      name: "key_7"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(-width * 0.24)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.46)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_8"

  - tool: modeling_transform_object
    params:
      name: "key_8"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.46)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_9"

  - tool: modeling_transform_object
    params:
      name: "key_9"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.105)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.085)"
      location:
        - "$CALCULATE(width * 0.24)"
        - "$CALCULATE(-depth * 0.56)"
        - "$CALCULATE(-height * 0.46)"

  # =============================
  # KEYPAD - Row 4 (*-0-#)
  # =============================
  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_star"

  - tool: modeling_transform_object
    params:
      name: "key_star"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.085)"
        - "$CALCULATE(height * 0.017)"
        - "$CALCULATE(depth * 0.11)"
      location:
        - "$CALCULATE(-width * 0.22)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.54)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_0"

  - tool: modeling_transform_object
    params:
      name: "key_0"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.095)"
        - "$CALCULATE(height * 0.018)"
        - "$CALCULATE(depth * 0.11)"
      location:
        - 0.0
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.54)"

  - tool: modeling_create_primitive
    params:
      primitive_type: Cylinder
      name: "key_hash"

  - tool: modeling_transform_object
    params:
      name: "key_hash"
      rotation: [1.5708, 0.0, 0.0]
      scale:
        - "$CALCULATE(width * 0.085)"
        - "$CALCULATE(height * 0.017)"
        - "$CALCULATE(depth * 0.11)"
      location:
        - "$CALCULATE(width * 0.22)"
        - "$CALCULATE(-depth * 0.55)"
        - "$CALCULATE(-height * 0.54)"

  # =============================
  # BUTTON BEVELS
  # =============================
  - tool: modeling_add_modifier
    params:
      name: "{obj}"
      modifier_type: "BEVEL"
      properties:
        width: 0.0003
        segments: 2
        limit_method: "ANGLE"
        angle_limit: 0.785398
    loop:
      variable: "obj"
      values:
        - "button_dpad"
        - "button_call"
        - "button_end"
        - "button_soft_left"
        - "button_soft_right"
        - "key_1"
        - "key_2"
        - "key_3"
        - "key_4"
        - "key_5"
        - "key_6"
        - "key_7"
        - "key_8"
        - "key_9"
        - "key_0"
        - "key_star"
        - "key_hash"
    description: Bevel all buttons and keys

  # =============================
  # COLLECTION ASSIGNMENT
  # =============================
  - tool: collection_manage
    params:
      action: "move_object"
      collection_name: "Phone_Body"
      object_name: "{obj}"
    loop:
      variable: "obj"
      values:
        - "body_shell"
        - "body_lattice"
        - "back_panel"
        - "antenna_base"
        - "antenna_rod"
        - "charging_port"
    description: Move body objects

  - tool: collection_manage
    params:
      action: "move_object"
      collection_name: "Phone_Front"
      object_name: "{obj}"
    loop:
      variable: "obj"
      values:
        - "front_lower_arc"
        - "front_top_eyelet"
        - "front_speaker_grille"
        - "front_keypad_ribs"
        - "side_trim_left"
        - "side_trim_right"
    description: Move front objects

  - tool: collection_manage
    params:
      action: "move_object"
      collection_name: "Phone_Screen"
      object_name: "{obj}"
    loop:
      variable: "obj"
      values:
        - "front_screen_frame"
        - "screen_glass"
    description: Move screen objects

  - tool: collection_manage
    params:
      action: "move_object"
      collection_name: "Phone_Buttons"
      object_name: "{obj}"
    loop:
      variable: "obj"
      values:
        - "button_dpad"
        - "button_call"
        - "button_end"
        - "button_soft_left"
        - "button_soft_right"
        - "key_1"
        - "key_2"
        - "key_3"
        - "key_4"
        - "key_5"
        - "key_6"
        - "key_7"
        - "key_8"
        - "key_9"
        - "key_0"
        - "key_star"
        - "key_hash"
    description: Move buttons and keys
